services:

  data-warehouse:
    image: postgres:14.2-alpine
    container_name: data_warehouse_pg
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - locadoras:/var/liv/postgresql
      
      # -- Inicializa o Banco de Dados que será o Data Warehouse -- #
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    


    


volumes:
  locadoras:
